name: Snakemake dry-run

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          auto-update-conda: true
          channels: conda-forge,bioconda,defaults
          channel-priority: strict
          activate-environment: snakemake-env

      - name: Install Snakemake
        shell: bash -el {0}
        run: |
          conda install -y snakemake

      - name: Snakemake dry-run
        shell: bash -el {0}
        run: |
          snakemake --use-conda --dry-run
